name: test
description: Data transfer between GroupSession and Google Calender.
version: 1.0.0+3
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: 0.5.0+1
  firebase_auth: 0.18.1+2
  google_sign_in: 4.5.5
  imagebutton: 0.0.6
  flutter_picker: 1.1.5
  xml: 4.5.1
  http: 0.12.2
  sprintf: 5.0.0
  googleapis: 0.56.1
  cupertino_icons: 1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/googlesignin.png
    - assets/googlesigninpress.png
    - assets/gs.jpeg
    - assets/gc.png
