name: increment build number
on:
  push:
    branches:
      - test

jobs:
  update_build_number:
    runs-on: ubuntu-latest
    name: update build number
    steps:
      - uses: actions/checkout@v3
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
            file: './pubspec.yaml'          # File to read from
            key-path: '["version"]' # Access the runs key then the using key and retuns the value.
      - name: increment build number
        id: increment_build_number
        run: |
          echo "next_version=$(echo "${{ steps.yaml-data.outputs.data }}" |awk 'BEGIN{FS="+"}{printf "%s+%d",$1,$2+1}')" >>$GITHUB_ENV
      - name: update pubspec.yaml
        id: update_pubspec_yaml
        uses: fjogeleit/yaml-update-action@main
        with:
            valueFile: 'pubspec.yaml'
            propertyPath: 'version'
            value: ${{ env.next_version }}
            commitChange: true
            message: 'update build number'
            createPR: false
            masterBranchName: main
            branch: test
