name: release stable version
on:
    push:
        branches:
            - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v3
      - name: get version number
        id: get_version_number
        uses: jbutcher5/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
            file: './pubspec.yaml'          # File to read from
            key-path: '["version"]' # Access the runs key then the using key and retuns the value.
      - name: generate release name
        id: generate_release_name
        run: echo "version=$(echo "${{ steps.get_version_number.outputs.data }}" |awk 'BEGIN{FS="+"}{print $1}')" >>$GITHUB_ENV
      - name: release
        id: release
        uses: ncipollo/release-action@v1
        with:
            tag: "v${{ env.version }}"
            name: "v${{ env.version }}"
            generateReleaseNotes: true
